// LP-7 stage A: does the FIRST decrypt arm spuriously succeed with a wrong key,
// and if it does, is there any path back to the second arm?
//
// MEASUREMENT ONLY. Generates its own material; opens, reads and writes NO wallet
// file and no wallet directory; changes no production code.
//
// Stage B already excluded the derivation (5,000 fresh mnemonics, 0 mismatches),
// so the defect is in whatever produces the guard's INPUT. The recovery path in
// CWallet tries the seed-derived obfuscation key FIRST and the master key only
// `if (!decOk)`. For a legacy wallet whose mnemonic sits under the MASTER key the
// first attempt therefore runs with a WRONG key, and AES-CBC + PKCS#7 accepts a
// wrong-key block whenever the trailing bytes happen to form valid padding.
//
// Three questions, per COORD:
//   (1) the spurious first-arm success rate against the REAL CCrypter::Decrypt;
//   (2) whether a guard REJECTION can fall through to the second arm;
//   (3) the per-run denominator - how many wrong-key attempts a suite run makes.
// BUILD (not wired into the Makefile, matching the other src/tools benches):
//
//   gcc -std=c11 -O2 -c depends/dilithium/ref/fips202.c -o /tmp/fips202.o
//   g++ -std=c++17 -O2 -I src -I .
//       src/tools/lp7_armprobe.cpp src/wallet/crypter.cpp
//       src/crypto/hmac_sha3.cpp src/crypto/sha3.cpp src/rpc/auth.cpp /tmp/fips202.o
//       -o lp7armprobe.exe -lcrypto -lssl -lbcrypt
//   (one command; wrapped here for width only. No continuation characters --
//    a comment line ending in a backslash is a LINE SPLICE, and this tree's
//    comment stripper fails closed on exactly that.)
//
//   ./lp7armprobe.exe 200000            # the rate
//   ./lp7armprobe.exe 200000 --emit-kat # the rate, plus the frozen KAT triple
//
// EXPECTED BAND: 0.3825% measured against a strict-PKCS#7 prediction of 0.3922%.
// A rate is NOT a pass/fail gate, which is why this is a bench and not a unit
// test; the pass/fail lives in wallet_encryption_at_rest_tests.cpp as a frozen
// KAT (test 2e-5) and a constructed-condition regression (test 2e-4).

#include <wallet/crypter.h>

#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <random>
#include <string>
#include <vector>

// KAT EMISSION (stage C). The RED arm for the fix must be a PINNED fixture, not a
// probabilistic test: a test that waits for a 0.38% event is a flake generator, and
// a test that asserts a RATE cannot say whether the fix works on any given wallet.
// So this emits the material of the FIRST spurious acceptance this seeded run
// produces - key, IV and ciphertext - which the unit test then freezes.
//
// Nothing here is wallet material. Every byte is generated by this probe own
// mt19937_64 at the fixed seed below, so the emitted triple is reproducible by
// re-running the probe and is not a secret of any kind.
static void emit_hex(const char* name, const std::vector<uint8_t>& v) {
    printf("    %-12s ", name);
    for (uint8_t b : v) printf("%02x", b);
    printf("\n");
}

int main(int argc, char** argv) {
    const long long N = (argc > 1) ? atoll(argv[1]) : 100000;
    const bool katMode = (argc > 2 && std::string(argv[2]) == "--emit-kat");
    printf("LP-7 stage A: wrong-key first-arm acceptance, N=%lld\n\n", N);

    // A realistic 24-word mnemonic length; the plaintext content is irrelevant to
    // the padding question, only its length matters for block layout.
    const std::string phrase =
        "abandon abandon abandon abandon abandon abandon abandon abandon "
        "abandon abandon abandon abandon abandon abandon abandon abandon "
        "abandon abandon abandon abandon abandon abandon abandon art";
    const std::vector<uint8_t> plain(phrase.begin(), phrase.end());

    std::mt19937_64 rng(0xA8107ULL);          // fixed seed: reproducible run
    auto rnd = [&rng](std::vector<uint8_t>& v) {
        for (auto& b : v) b = static_cast<uint8_t>(rng() & 0xff);
    };

    long long accepted = 0, decryptedToSamePlaintext = 0;
    std::vector<size_t> acceptedLens;

    for (long long i = 0; i < N; ++i) {
        std::vector<uint8_t> realKey(WALLET_CRYPTO_KEY_SIZE), wrongKey(WALLET_CRYPTO_KEY_SIZE);
        std::vector<uint8_t> iv(16);
        rnd(realKey); rnd(wrongKey); rnd(iv);

        // Encrypt under the REAL key (this is the master-key slot in the fixture).
        CCrypter enc;
        std::vector<uint8_t> ct;
        if (!enc.SetKey(realKey, iv) || !enc.Encrypt(plain, ct)) {
            printf("  ENCRYPT FAILED at i=%lld - probe cannot proceed\n", i);
            return 2;
        }

        // Now attempt the FIRST arm: decrypt with the WRONG (obfuscation) key.
        CCrypter dec;
        std::vector<uint8_t> out;
        if (dec.SetKey(wrongKey, iv) && dec.Decrypt(ct, out)) {
            if (katMode && accepted == 0) {
                printf("KAT: first spurious wrong-key acceptance at i=%lld\n", i);
                emit_hex("realKey", realKey);
                emit_hex("wrongKey", wrongKey);
                emit_hex("iv", iv);
                emit_hex("ciphertext", ct);
                emit_hex("garbageOut", out);
                printf("    garbage_len  %zu (plaintext is %zu)\n\n",
                       out.size(), plain.size());
            }
            ++accepted;
            acceptedLens.push_back(out.size());
            if (out == plain) ++decryptedToSamePlaintext;   // must never happen
        }
    }

    const double rate = (double)accepted / (double)N;
    printf("(1) WRONG-KEY FIRST-ARM ACCEPTANCE\n");
    printf("    attempts ................. %lld\n", N);
    printf("    CCrypter::Decrypt said OK  %lld\n", accepted);
    printf("    measured rate ............ %.6f  (%.4f%%)\n", rate, 100.0 * rate);
    // Strict PKCS#7 over a uniform final block: sum_{k=1..16} (1/256)^k.
    double expect = 0.0, term = 1.0 / 256.0;
    for (int k = 1; k <= 16; ++k) { expect += term; term /= 256.0; }
    printf("    strict-PKCS#7 prediction .. %.6f  (%.4f%%)\n", expect, 100.0 * expect);
    printf("    -> %s\n", (rate < expect * 3 && rate > expect / 3)
        ? "CONSISTENT with strict padding validation (EVP_DecryptFinal_ex)"
        : "NOT consistent with strict validation - the check is laxer than assumed");
    printf("    recovered == real plaintext: %lld  (must be 0; a wrong key must never\n"
           "                                 reproduce the phrase)\n", decryptedToSamePlaintext);
    if (!acceptedLens.empty()) {
        size_t mn = acceptedLens[0], mx = acceptedLens[0];
        for (size_t l : acceptedLens) { if (l < mn) mn = l; if (l > mx) mx = l; }
        printf("    accepted-garbage lengths .. %zu..%zu bytes (plaintext is %zu)\n",
               mn, mx, plain.size());
    }

    printf("\n(2) CONTROL FLOW - can a guard REJECTION reach the second arm?\n");
    printf("    Read from src/wallet/wallet.cpp, and it is unambiguous:\n");
    printf("      decOk = <obfuscation-key decrypt>          // arm 1\n");
    printf("      if (!decOk) { decOk = <master-key decrypt>; }   // arm 2, gated on FAILURE\n");
    printf("      if (!decOk) { rollback(); return false; }\n");
    printf("      verified = MnemonicReDerivesSeed(...)      // the guard\n");
    printf("      if (!verified) { DEFER }                   // <-- no path back to arm 2\n");
    printf("    NO. The second arm is gated on the first DECRYPT failing, not on the\n");
    printf("    recovered phrase failing the identity guard. So a spurious arm-1\n");
    printf("    acceptance PRE-EMPTS the correct arm, and because key, IV and\n");
    printf("    ciphertext are all fixed for a given wallet, it does so on EVERY\n");
    printf("    future unlock. That wallet can never migrate.\n");
    printf("    FIX SHAPE (regardless of the rate): try each arm until one produces a\n");
    printf("    phrase that VERIFIES, not until one produces a phrase that DECRYPTS.\n");
    return 0;
}
